### ISSUE TITLE
Can't change armor type?

### ISSUE THREAD

**Issue by brettsmods** [CutFlame/MCDSaveEdit#10]
I can change weapons, etc by clicking on the picture on the far right of the editor, but this doesn't seem to work with armor? Is this intentional or a bug? 

Thanks.

**Comment by CutFlame** [comment]
This was done intentionally. I wanted to do some more testing with changing armor because I didn't have in the ability to change armor properties as well. So I was skeptical that the game would recognize an armor with the unexpected armor properties. I have since then discovered that the game allows this and my next release will allow both changing armor and armor properties (which is really exciting). This will be in version 1.2.5
