### ISSUE TITLE
support for switch 

### ISSUE THREAD

**Issue by Anitek16** [CutFlame/MCDSaveEdit#103]
would be good to have a support for switch versions aswell?

**Comment by maksim789456** [comment]
All save files (including saving the MCD character) on Switch are encrypted in a special way and it is not possible to decrypt them for modification without special keys.
If you have a flashed or chip-based console, then you can decrypt the character save files and change them.
Otherwise, the only way to change the save is to transfer the save from Switch to Pc.
[Instructions](https://help.minecraft.net/hc/en-us/articles/360043504492) for transferring save from Mojang (you must have a Switch Online subscription to transfer)

**Comment by ACKREIK** [comment]
i mean you CAN do this via a few programs, needs HB though.

Grab save file from switch via checkpoint or ur save editor choice
then drop the raw file (no .bat ending) onto this program a few times, until you get a .bat https://github.com/HellPie/DungeonTools
put the .bat as your pc save file and save again
then use the editor on pc
drop the .bat a couple times until you get the raw file again
move back to switch
make sure to save so it converts save


done.
worked for me at least

**Comment by CutFlame** [comment]
If you guys could provide me some example save files pulled from the switch, I could spend some time getting MCDSaveEdit to work with them.

**Comment by ACKREIK** [comment]
ok hold on, i should still have my saves as the raw save file (how the switch uses it)

**Comment by ACKREIK** [comment]
[fullsave.zip](https://github.com/CutFlame/MCDSaveEdit/files/8379832/fullsave.zip)

**Comment by ACKREIK** [comment]
also switch saves do work with mcedit, though they do need to be converted to .dat save first, then converted back

**Comment by wtfatty** [comment]
> also switch saves do work with mcedit, though they do need to be converted to .dat save first, then converted back

How can you convert it back to the Switch raw format? 
Every time i drop a .dat file on the program it just convert it back to .json and so on.
