### ISSUE TITLE
I don't load the images

### ISSUE THREAD

**Issue by Rojitas7** [CutFlame/MCDSaveEdit#130]
Hello, I have a problem with the application and it is that the images do not load and that makes it quite difficult for me to modify things and when I have to look for the .pak files they do not appear, any solution?

**Comment by LuckyPants12** [comment]
are you using the version 1.5.2,0 from here? if so please use the version i have compiled in my github repository in the releases pahe, just go to my profile and you will see my fork. download either one of these releases.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/75674528/165015575-4d96130a-3854-4671-b661-c173358abae9.png">
You can download the non-pre release one , the pre release allows you to put the AES key yourself so that you dont need to download it another times and can keep using the same.

As for the pak not appearing, where did you download mc dungeons from? the pak location can change if you downloaded it from xbox or launcher.
