### ISSUE TITLE
The link for storepatcher.exe appears on Google's Unsafe Sites list

### ISSUE THREAD

**Issue by jgentil** [CutFlame/MCDSaveEdit#16]
https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fdocs.dungeonsworkshop.net%2Fgettingstarted%2F

What's going on with that?  Does storepatcher have malware??

**Comment by jgentil** [comment]
![image](https://user-images.githubusercontent.com/102330/102702984-c9699200-422e-11eb-95ee-bf34c7ff2f4c.png)

When scanning it with Windows Defender...

**Comment by jgentil** [comment]
![image](https://user-images.githubusercontent.com/102330/102703010-16e5ff00-422f-11eb-8910-1c327439a7f0.png)
When scanning with Windows Defender....

**Comment by CutFlame** [comment]
The storepatcher.exe is a powershell script put through a program called [PS2EXE](https://github.com/MScholtes/PS2EXE). This program was recently been flagged because someone used it with their virus script. I did not write the script for storepatcher.exe but I have seen the code for it and can confirm it does not have malware nor dishonest intent. This red flag has been reported to the anti-virus websites as a false positive but these things take time to get cleared.
