### ISSUE TITLE
not loading properly

### ISSUE THREAD

**Issue by theotheronoeofem** [CutFlame/MCDSaveEdit#8]
whenever i load the editor everything is white, i can only see outlines of boxes
![Capture](https://user-images.githubusercontent.com/74156218/98484166-764ef900-2205-11eb-974c-1bfdeb30759b.PNG)

**Comment by CutFlame** [comment]
This is by design. It can't show any of the images from the game because it can't detect that you have the game installed. Please try the latest version, as I have added support for more versions of the game. Regardless if you have the game installed or not, it should still be able to open your save files and edit them, it just won't look as cool or be as user friendly.
